Add status_to_string function
dyc3/discord-pokemon-battles pull request #25
Opened 2021-03-24 03:40 UTC by A-very-Cunning-ham

Converts the integer representation of a status effect to its respective status name
Closes #19

2021-03-24 03:44 UTC, dyc3 requested changes
- This will fail if the status condition has multiple volatile status conditions, or a non-volatile condition and a volatile status condition.
- The docstring is also missing what exceptions this function can raise.
- When this function fails, it'll raise a `KeyError`, which might be somewhat cryptic. Would prefer an error with a custom message.

2021-03-25 01:35 UTC, A-very-Cunning-ham commented on util.py
> +		raise ValueError
please let me know if i should be handling errors in a better or different way than this

2021-03-25 03:12 UTC, dyc3 requested changes

2021-03-25 03:12 UTC, dyc3 commented on util.py
> +	except:
Would prefer this to not be a catch all

2021-03-25 03:50 UTC, dyc3 approved these changes

2021-03-25 03:50 UTC, merged